name: deploy to VPS

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy sources via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase : ${{ secrets.SSH_KEY_PASSPHRASE }}
        source: "slao_bot/*.py"
        target: "bot"
        strip_components: 1
    - name: setup dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase : ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          cd bot
          python3 -m venv env
          python -m pip install --upgrade pip
          pip install -r requirements.txt